version: "3.9"

services:
  dev_db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ROOT
      POSTGRES_PASSWORD: ROOT_PASWORD
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"

  test_db:
    container_name: test_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ROOT
      POSTGRES_PASSWORD: ROOT_PASSWORD
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"